spring.application.name=textil-app
# Puerto del servidor
server.port=8081

# Configuraci�n de H2
spring.datasource.url=jdbc:h2:mem:textil-db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Dialecto de Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Crear autom�ticamente la base de datos
spring.jpa.hibernate.ddl-auto=update

# Mostrar SQL en consola
spring.jpa.show-sql=true

# Formatear SQL
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
